### ISSUE TITLE
Empty Settings Window

### ISSUE THREAD

**Issue by Endor8** [iArunava/Assistant-Reminder#5]
Hi.
I using Firefox 60.0.1 an Windows 7.
When I open the settings by click on setting in the popup window,
I got only this:
![bild1](https://user-images.githubusercontent.com/1267601/40276625-3a47f8b2-5c0f-11e8-82da-f63c4a50220d.png)
Is this correct?
Cheers
Endor

**Comment by Endor8** [comment]
I reinstalled the add-on and now it works .
cheers
Endor

**Comment by iArunava** [comment]
Great to hear that @Endor8 
Do let me know if the 'Notification sound' feature works
